### ISSUE TITLE
Add `logsumexp`

### ISSUE THREAD

**Issue by gdalle** [cjdoris/LogarithmicNumbers.jl#10]
Hi, and thanks for the great package!
At the moment I see no definition of [`logsumexp`](https://en.wikipedia.org/wiki/LogSumExp) for logarithmic numbers, even though it sounds pretty easy to make (it is basically a sum).
Would you be open to a PR regarding this?

**Comment by gdalle** [comment]
Maybe we would want to extend the version from https://github.com/JuliaStats/LogExpFunctions.jl?

**Comment by cjdoris** [comment]
I guess we could define
```julia
logsumexp(xs) = log(sum(x->exp(ULogarithmic, x), xs))
```
and similar for some other functions in `LogExpFunctions.jl`, but why not just use that package instead?

**Comment by gdalle** [comment]
Because I want to try working with LogarithmicNumbers for an HMM implementation, and I think their function would deserve to be specialized. Besides, LogExpFunctions has many more dependencies

**Comment by cjdoris** [comment]
Don't forget a logarithmic number represents the number, not the logarithm (it just happens to store the logarithm).

So if you have a vector `xs` of logarithmic numbers and want the sum, you just do `sum(xs)`. You'd use `logsumexp` if you actually have a vector of logarithms (as `Float64` say) and want the logarithm of the sum. You probably don't mean to do `logsumexp(xs)` on a vector of logarithmic numbers.
