### ISSUE TITLE
Allowing default constructor?

### ISSUE THREAD

**Issue by GiggleLiu** [cjdoris/LogarithmicNumbers.jl#3]
Great tool! But I find every constructors of `ULogarithmic` are overwritten by `converter`s.
Default constructor can be useful, a possible using case of a default constructor is inserting a Dual number for gradient computation.

```julia
julia> using ForwardDiff: Dual

julia> ULogarithmic(Dual(0.4, 1.0))
exp(Dual{Nothing}(-0.916290731874155,2.5))
```

I don't want it do the computation automatically. Is it possible to do so? If not, are you willing to accept a PR?

My opinion is `convert(Logarithmic, x)` does the convertion. The default constructor should be untouched.

**Comment by GiggleLiu** [comment]
Another possible issue:
```julia
julia> ULogarithmic{Float64}(1e300)
exp(690.7755278982137)

julia> ULogarithmic{Float64}(1e350)
ERROR: syntax: overflow in numeric constant "1e350"
Stacktrace:
 [1] top-level scope at REPL[14]:0
```

**Comment by GiggleLiu** [comment]
Well, I find the `exp(::ULogarithmic, x)` interface.
Still, I believe `Base.convert` is more intuitive than doing casting automatically.

**Comment by cjdoris** [comment]
Indeed, `exp(::ULogarithmic, x)` is the constructor, which makes sense because its result is (mathematically) equal to `exp(x)`. I considered `ULogarithmic(x)` as being a constructor too, but this deviates a lot from the standard Julia behaviour: if `T <: Number` is a builtin type, then `T(x)` and `convert(T,x)` are mostly equivalent.

**Comment by cjdoris** [comment]
Your other issue is a Julia limitation. If you want to construct really big or small logarithmic numbers, use `exp`.

**Comment by cjdoris** [comment]
I'd be interested to hear if `ForwardDiff` works in combinations with logarithmic numbers, or what any sticking points are.
