### ISSUE TITLE
Fixed-point angle

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/LogarithmicNumbers.jl#5]
Hi,

I've been thinking of making a package similar to yours. I could fork it, or reuse it, but now realize its GPLv3, so maybe I shouldn't look at it more in case... I want to use a different license.

Anyway, I think you're doing standard stuff, except for polar form, what was my thought too, and then some extra ideas to overcome the cons. I know the pros and cons, but it seems your implementation forces the angle to be of the same type. Am I wrong?

**Comment by cjdoris** [comment]
Hi, sorry just noticed this. I'm going to relicense all my repos to MIT. You're welcome to contribute to this one.

The complex logarithmic numbers could definitely be improved. I don't think anybody uses them, myself included, so have considered just removing them.

**Comment by cjdoris** [comment]
Closed because I've removed the complex logarithmics, for simplicity. I'm not aware of anyone using them.

**Comment by PallHaraldsson** [comment]
Good to know, if I needed this. Do you need to update version because of semver? Or would that only apply after 1.0 (or if you had actual suspected users of CL...).

**Comment by cjdoris** [comment]
Yeah I'll release a new version.
